# Generated by Django 3.2.7 on 2021-09-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0003_auto_20210908_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='op-rs.png', upload_to=''),
        ),
    ]
